<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Central America Standard Time">
<General productName="Vugen" productVer="12" os="" host="TEKSJOPCLR29"><DocLocation><![CDATA[C:\Users\Tek\Documents\VuGen\Scripts\WebHttpHtml17]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[WebHttpHtml17]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Url: streaming-test]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/6/2016 - 14:03:02]]></Time>
<TimeTick>1467835382</TimeTick>
<NodeArgs eType="General" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Url: streaming-test]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Url: Index-DASH.html]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/6/2016 - 14:03:03]]></Time>
<TimeTick>1467835383</TimeTick>
<NodeArgs eType="General" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[Url: Index-DASH.html]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t2.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Service: Concurrent Group - start]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Concurrent Group started</CENTER>]]></Details>
<Time><![CDATA[7/6/2016 - 14:03:03]]></Time>
<TimeTick>1467835383</TimeTick>
<NodeArgs eType="General" icon="4" nRep="8" >
<Disp><![CDATA[Service: Concurrent Group - start]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Url: bootstrap.min.css]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Url: bootstrap.min.css registered successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/6/2016 - 14:03:03]]></Time>
<TimeTick>1467835383</TimeTick>
<NodeArgs eType="General" icon="3" nRep="9" >
<Disp><![CDATA[Url: bootstrap.min.css]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Url: jquery.min.js]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Url: jquery.min.js registered successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/6/2016 - 14:03:03]]></Time>
<TimeTick>1467835383</TimeTick>
<NodeArgs eType="General" icon="3" nRep="10" >
<Disp><![CDATA[Url: jquery.min.js]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Url: bootstrap.min.js]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Url: bootstrap.min.js registered successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/6/2016 - 14:03:03]]></Time>
<TimeTick>1467835383</TimeTick>
<NodeArgs eType="General" icon="3" nRep="11" >
<Disp><![CDATA[Url: bootstrap.min.js]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Url: dash.all.js]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Url: dash.all.js registered successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[7/6/2016 - 14:03:03]]></Time>
<TimeTick>1467835383</TimeTick>
<NodeArgs eType="General" icon="3" nRep="12" >
<Disp><![CDATA[Url: dash.all.js]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Service: Concurrent Group - end]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Concurrent Group ended</CENTER>]]></Details>
<Time><![CDATA[7/6/2016 - 14:03:30]]></Time>
<TimeTick>1467835410</TimeTick>
<NodeArgs eType="General" icon="5" nRep="13" >
<Disp><![CDATA[Service: Concurrent Group - end]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Service: Stream Open]]></Obj>
<Details plainTxt="False" ><![CDATA[ Stream ID=1, URL="http://kalimanjaro.hpeswlab.net/streaming-test/elephants_dream_480p_heaac5_1.mpd" opened]]></Details>
<Time><![CDATA[7/6/2016 - 14:03:31]]></Time>
<TimeTick>1467835411</TimeTick>
<NodeArgs eType="General" icon="6" nRep="14" >
<Disp><![CDATA[Service: Stream Open]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Service: Stream Play]]></Obj>
<Details plainTxt="False" ><![CDATA[ Stream ID=1 started palying]]></Details>
<Time><![CDATA[7/6/2016 - 14:04:30]]></Time>
<TimeTick>1467835470</TimeTick>
<NodeArgs eType="General" icon="6" nRep="15" >
<Disp><![CDATA[Service: Stream Play]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Service: Stream Pause]]></Obj>
<Details plainTxt="False" ><![CDATA[ Stream ID=1 paused]]></Details>
<Time><![CDATA[7/6/2016 - 14:04:35]]></Time>
<TimeTick>1467835475</TimeTick>
<NodeArgs eType="General" icon="6" nRep="16" >
<Disp><![CDATA[Service: Stream Pause]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Service: Stream Play]]></Obj>
<Details plainTxt="False" ><![CDATA[ Stream ID=1 started palying]]></Details>
<Time><![CDATA[7/6/2016 - 14:05:49]]></Time>
<TimeTick>1467835549</TimeTick>
<NodeArgs eType="General" icon="6" nRep="17" >
<Disp><![CDATA[Service: Stream Play]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Service: Stream Stop]]></Obj>
<Details plainTxt="False" ><![CDATA[ Stream ID=1 stoped]]></Details>
<Time><![CDATA[7/6/2016 - 14:05:49]]></Time>
<TimeTick>1467835549</TimeTick>
<NodeArgs eType="General" icon="6" nRep="18" >
<Disp><![CDATA[Service: Stream Stop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Service: Stream Close]]></Obj>
<Details plainTxt="False" ><![CDATA[ Stream ID=1 closed]]></Details>
<Time><![CDATA[7/6/2016 - 14:05:49]]></Time>
<TimeTick>1467835549</TimeTick>
<NodeArgs eType="General" icon="6" nRep="19" >
<Disp><![CDATA[Service: Stream Close]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/6/2016 - 14:03:00" eTime="7/6/2016 - 14:05:49" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" status="Passed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T17" iterID="1" >
<Action rID="T18">
<AName><![CDATA[Action]]></AName>
<Summary sTime="7/6/2016 - 14:05:49" eTime="7/6/2016 - 14:05:49" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="22" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="7" nRep="21" >
<Disp><![CDATA[WebHttpHtml17 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Action rID="T19">
<AName><![CDATA[vuser_end]]></AName>
<Summary sTime="7/6/2016 - 14:05:49" eTime="7/6/2016 - 14:05:49" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="25" >
<Disp><![CDATA[vuser_end Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="7/6/2016 - 14:02:58" eTime="7/6/2016 - 14:05:50" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="4" status="Passed" >
<Disp><![CDATA[Test WebHttpHtml17 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>